import React from 'react';
import MarketingPageLayout from '../../../components/MarketingPageLayout';

export const metadata = {
  title: 'AI Favicon Generator | Create Website Favicons Instantly',
  description: 'Generate unique, brand-matching favicons for your website with AI. Stand out in the browser tab.',
};

export default function FaviconGeneratorPage() {
  return (
    <MarketingPageLayout
      h1Title={
        <>
          Generate <span className="bg-gradient-to-r from-primary-600 to-accent-500 bg-clip-text text-transparent">Favicons</span> Fast
        </>
      }
      h2Subtitle="Make your website stand out in every browser tab with a unique, custom favicon logo generated by AI."
    />
  );
}
